
version: 0.2

env:
  exported-variables: # https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
    - CODEBUILD_WEBHOOK_HEAD_REF
    - CODEBUILD_WEBHOOK_TRIGGER

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - printf "CODEBUILD_WEBHOOK_BASE_REF = ${CODEBUILD_WEBHOOK_BASE_REF}\nCODEBUILD_WEBHOOK_HEAD_REF = ${CODEBUILD_WEBHOOK_HEAD_REF}\nCODEBUILD_WEBHOOK_TRIGGER  = ${CODEBUILD_WEBHOOK_TRIGGER}\nCODEBUILD_INITIATOR        = ${CODEBUILD_INITIATOR}\n"
      - git log -1
      - printf "Node.js = $(node --version)\nNPX     = v$(npx --version)\nYarn    = v$(yarn --version)\n"
  build:
    commands:
      - cd pipeline-example-frontend

      - |
        if case $CODEBUILD_INITIATOR in codepipeline*) true;; *) false;; esac; then
          npm install
          echo Finish install API Dependencies...

          echo Entering Build Phase
          npm run build
          echo Finish Build Phase Successfully...

          aws s3 sync dist/pipeline-example-frontend/ s3://${FRONTEND_BUCKET} --delete
        else
          echo "Build not triggered by CodePipeline, skipping deploy..."
        fi

cache:
  paths:
    - '/root/.yarn-cache/**/*'
    - 'node_modules/**/*'
