# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
AWSTemplateFormatVersion: "2010-09-09"
Description: "New BTFIT Backoffice Frontend CodeBuild creation (Deploy)"

Parameters:
  Application:
    Description: "BTFIT Backoffice Frontend build and deploy codebuild"
    Type: "String"
    Default: "btfit-backoffice-angular"
  Environment:
    Type: "String"
    AllowedValues: ["preprod", "prod"]
  Branch:
    Type: "String"
    AllowedValues: ["dev", "master"]
  BuildSpec:
    Type: "String"
    Default: ".aws/codebuild/buildspec/build-deploy-pt.yml"
  ConnectionId:
    Type: "String"
  TimeoutInMinutes:
    Type: "Number"
    Default: 10
  QueuedTimeoutInMinutes:
    Type: "Number"
    Default: 5
  SourceLocation:
    Type: "String"
    Default: "https://tokenlab-builder@bitbucket.org/tokenlab/btfit-backoffice-angular.git"
  FrontendBucket:
    Type: "String"
  CloudFrontDistribution:
    Type: "String"
  ServiceRole:
    Type: "String"

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod" ]

Resources:
  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    DependsOn:
      - DeployCodeBuildProject
    Properties:
      Name: !Sub "frontend-${Application}-deploy-pipeline"
      RoleArn: !Ref ServiceRole
      ArtifactStore:
        Type: S3
        Location: !Sub codepipeline-artifact-${AWS::AccountId}
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Owner: AWS
                Category: Source
                Version: '1'
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Sub "arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/${ConnectionId}"
                FullRepositoryId: "tokenlab/btfit-backoffice-angular"
                BranchName: !Ref Branch
                OutputArtifactFormat: "CODEBUILD_CLONE_REF"
              InputArtifacts: []
              OutputArtifacts:
                - Name: 'SourceArtifact'
        - Fn::If:
            - IsProd
            - Name: Hold
              Actions:
                - Name: DeployApproval
                  ActionTypeId:
                    Owner: AWS
                    Category: Approval
                    Version: '1'
                    Provider: Manual
            - !Ref "AWS::NoValue"
        - Name: BuildAndDeployCodeBuild
          Actions:
            - Name: DeployCodeBuild
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref DeployCodeBuildProject
              InputArtifacts:
                - Name: 'SourceArtifact'
              OutputArtifacts: []

  DeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "frontend-${Application}-codebuild"
      ServiceRole: !Ref ServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: ENV
            Type: PLAINTEXT
            Value: !Ref Environment

          - Name: FRONTEND_BUCKET
            Type: PLAINTEXT
            Value: !Ref FrontendBucket

          - Name: CLOUDFRONT_DISTRIBUTION
            Type: PLAINTEXT
            Value: !Ref CloudFrontDistribution

          - Name: AWS_S3_BUCKET
            Type: PLAINTEXT
            Value: !Ref FrontendBucket
      Source:
        BuildSpec: !Sub "${BuildSpec}"
        Location: !Ref SourceLocation
        Type: BITBUCKET
      SourceVersion: !Sub "${Branch}"
      TimeoutInMinutes: !Sub "${TimeoutInMinutes}"
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_SOURCE_CACHE
      LogsConfig:
        S3Logs:
          Status: ENABLED
          Location: !Sub "codepipeline-artifact-${AWS::AccountId}/.codebuild_logs/${Application}"
        CloudWatchLogs:
          Status: ENABLED
      QueuedTimeoutInMinutes: !Sub "${QueuedTimeoutInMinutes}"

