# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
AWSTemplateFormatVersion: "2010-09-09"
Description: "CodeBuild creation (Deploy)"

Parameters:
  Application:
    Description: "build and deploy codebuild"
    Type: "String"
    Default: "pipeline-example"
  BuildSpec:
    Type: "String"
    Default: "pipeline-example-frontend/.aws/codebuild/buildspec/build-deploy.yml"
  ConnectionId:
    Type: "String"
  TimeoutInMinutes:
    Type: "Number"
    Default: 10
  QueuedTimeoutInMinutes:
    Type: "Number"
    Default: 5
  SourceLocation:
    Type: "String"
    Default: "https://github.com/Zotesso/pipeline-examples.git"
  FrontendBucket:
    Type: "String"
  ServiceRole:
    Type: "String"

Resources:
  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    DependsOn:
      - DeployCodeBuildProject
    Properties:
      Name: !Sub "frontend-${Application}-deploy-pipeline"
      RoleArn: !Ref ServiceRole
      ArtifactStore:
        Type: S3
        Location: !Sub codepipeline-artifact-${AWS::AccountId}
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Owner: AWS
                Category: Source
                Version: '1'
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Sub "arn:aws:codestar-connections:${AWS::Region}:${AWS::AccountId}:connection/${ConnectionId}"
                FullRepositoryId: "Zotesso/pipeline-examples"
                BranchName: dev
                OutputArtifactFormat: "CODEBUILD_CLONE_REF"
              InputArtifacts: []
              OutputArtifacts:
                - Name: 'SourceArtifact'
        - Name: Hold
          Actions:
            - Name: DeployApproval
              ActionTypeId:
                Owner: AWS
                Category: Approval
                Version: '1'
                Provider: Manual
        - Name: BuildAndDeployCodeBuild
          Actions:
            - Name: DeployCodeBuild
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref DeployCodeBuildProject
              InputArtifacts:
                - Name: 'SourceArtifact'
              OutputArtifacts: []

  DeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "frontend-${Application}-codebuild"
      ServiceRole: !Ref ServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: FRONTEND_BUCKET
            Type: PLAINTEXT
            Value: !Ref FrontendBucket
      Source:
        BuildSpec: !Sub "${BuildSpec}"
        Location: !Ref SourceLocation
        Type: GITHUB
      SourceVersion: dev
      TimeoutInMinutes: !Sub "${TimeoutInMinutes}"
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_SOURCE_CACHE
      QueuedTimeoutInMinutes: !Sub "${QueuedTimeoutInMinutes}"

