# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html
AWSTemplateFormatVersion: "2010-09-09"
Description: "CodeBuild creation (Only Build)"

Parameters:
  Application:
    Description: "BTFIT Backoffice Frontend build and lint codebuild"
    Type: "String"
    Default: "pipeline-example-frontend"
  TimeoutInMinutes:
    Type: "Number"
    Default: 5
  QueuedTimeoutInMinutes:
    Type: "Number"
    Default: 5
  BuildSpec:
    Type: "String"
    Default: ".aws/codebuild/buildspec/lint-build-test.yml"

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${Application}-codebuild-project-build"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
      Source:
        BuildSpec: !Sub "${BuildSpec}"
        Location: https://github.com/Zotesso/pipeline-examples.git
        Type: GITHUB 
      TimeoutInMinutes: !Sub "${TimeoutInMinutes}"
      Triggers:
        Webhook: true
        FilterGroups:
        FilterGroups:
          - - Type: EVENT
              Pattern: PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED
            - Type: BASE_REF
              Pattern: !Sub "^refs/heads/dev"
            - Type: FILE_PATH
              Pattern: "/pipeline-example-frontend/"
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_SOURCE_CACHE
      QueuedTimeoutInMinutes: !Sub "${QueuedTimeoutInMinutes}"


  CodeBuildServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub "${Application}-codebuild-build-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: [codebuild.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: !Sub "${Application}-codebuild-build-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"

Outputs:
  RoleName:
    Value: !Sub "${Application}-role-codebuild-build"
